### GET Request to Retrieve Contact Information
GET https://cse-341-project1-lfo7.onrender.com/users/

### GET Request to Retrieve One Contact Information
GET https://cse-341-project1-lfo7.onrender.com/users/6483ce023f46080356e0c6d5

### GET Request to Retrieve One Contact Information
GET https://cse-341-project1-lfo7.onrender.com/users/6483ce023f46080356e0c6d6

### GET Request to Retrieve One Contact Information
GET https://cse-341-project1-lfo7.onrender.com/users/6483ce023f46080356e0c6d7

### GET Request to Retrieve One Contact Information
GET https://cse-341-project1-lfo7.onrender.com/users/6483ce023f46080356e0c6d8

### GET Request to Retrieve Contact Information
GET http://localhost:3000/users/
APIKEY: Ezl0961tEpx2UxTZ5v2uKFK91qdNAr5npRlMT1zLcE3Mg68Xwaj3N8Dyp1R8IvFenrVwHRllOUxF0Og00l0m9NcaYMtH6Bpgdv7N

### GET Request to Retrieve Contact Information
GET http://localhost:3000/users/6483ce023f46080356e0c6d5
APIKEY: Ezl0961tEpx2UxTZ5v2uKFK91qdNAr5npRlMT1zLcE3Mg68Xwaj3N8Dyp1R8IvFenrVwHRllOUxF0Og00l0m9NcaYMtH6Bpgdv7N

### Save a User 
POST http://localhost:3000/users HTTP/1.1
APIKEY: Ezl0961tEpx2UxTZ5v2uKFK91qdNAr5npRlMT1zLcE3Mg68Xwaj3N8Dyp1R8IvFenrVwHRllOUxF0Og00l0m9NcaYMtH6Bpgdv7N
content-type: application/json

{
    "email": "brenda@test.com",
    "username": "brenda@test.com",
    "name": "Brenda",
    "ipaddress": "94.121.163.68"
}

### Update a User 
PUT http://localhost:3000/users/65b161a9bfc61d0d10b9b69d HTTP/1.1
APIKEY: Ezl0961tEpx2UxTZ5v2uKFK91qdNAr5npRlMT1zLcE3Mg68Xwaj3N8Dyp1R8IvFenrVwHRllOUxF0Og00l0m9NcaYMtH6Bpgdv7N
content-type: application/json

{
    "email": "brenditak@test.com",
    "username": "brenditak@test.com",
    "name": "Brenda Q",
    "ipaddress": "91.221.163.68"
}

### Delete a User 
DELETE http://localhost:3000/users/65b161a9bfc61d0d10b9b68d HTTP/1.1
APIKEY: Ezl0961tEpx2UxTZ5v2uKFK91qdNAr5npRlMT1zLcE3Mg68Xwaj3N8Dyp1R8IvFenrVwHRllOUxF0Og00l0m9NcaYMtH6Bpgdv7N

